### ISSUE TITLE
Test Api Token access in Verify Conditions step

### ISSUE THREAD

**Issue by BinToss** [droidsolutions/semantic-release-nuget#927]
1. Create package(s).
  - A. Pack with previous, latest, or minimum prerelease version; push it with `--skip-duplicate`.
  - B. Bundle a minver, [deterministic-ated](https://github.com/Kuinox/NupkgDeterministicator) dummy package. Make one copy per Package ID. Push each dummy package with the real private keys. [NuGet.org has a QA server](https://int.nugettest.org) that _should_ work in lieu of [`--dry-run`](https://github.com/NuGet/Home/issues/13475). Can we unlist specific package versions without unlisting the entire package?
3. Push package(s) to configured registries with private keys. If multiple package ID per registry, there may be as many as one private key per package ID for that registry. As noted, Nuget.org should be replaced with https://int.nugettest.org/ for the sake of token verification.

I started working on [something similar](https://github.com/HaloSPV3/HCE.Shared/blob/b210028aff828aaec9455d1ff7b461e77ae996be/src/dotnet/NugetRegistryInfo.ts#L226) when I realized it would be a great feature to have in this project! No more partial, failed releases because a package failed to push!

**Comment by Kampfmoehre** [comment]
Hi there,

first of all, I understand the pain of having a release and failing the push, did encounter it myself last time my NuGET API key expired and I forgot to update the secret in a repo.
However I don't like the idea of pushing a package each time the verify step runs. Depending on the CI config it could run a lot of times, we don't even know if there is going to be a new release this time, because that is determined in a later step.
As for using the previous package this can be cumbersome, for once we don't necessarily have one, also it is not easy to determine what version it would have if we have one. Getting the last release is also done in a later step.

Unfortunately I don't really have a solution at this moment so other suggestions are welcome.

**Comment by BinToss** [comment]
> However I don't like the idea of pushing a package each time the verify step runs. Depending on the CI config it could run a lot of times, we don't even know if there is going to be a new release this time, because that is determined in a later step.

Performing token verification during `prepare` would solve part of the issue. Pushes would still need to run for each Token-Registry or PackageId-Token-Registry permutation. And that's assuming the packages are unsigned. 
Performance hits could be mitigated by parallelizing via an array of calls to `execAsync` (where `const execAsync = promisify(exec);`) and `Promise.all`.
Bandwidth constraints and data limits aren't a concern. I learned how to to `dotnet pack` a 1.9 KiB dummy nupkg. It's just the minimum nupkg metadata files and a 0-byte Content file.

> As for using the previous package, this can be cumbersome, for once we don't necessarily have one. Also, it is not easy to determine what version it would have if we have one. Getting the last release is also done in a later step.

Think of it as querying the latest version (incl. prereleases) of the package available from the registries. If there's no result with the exact PackageId, then the package has never been pushed to that registry.

Because GitHub and GitLab require tokens for queries of public endpoints and packages, they'll need to be `dotnet nuget add source`ed with the token set as the password and username set to...anything. As an aside, it might be easier to tell users to set all NuGet sources _before_ running semantic-release.
Finally, parse the output of `dotnet package search $(PackageId) --format json --prerelease` for results from each registry.

```json
// dotnet package search HXE --format json --prerelease
{
  "version": 2,
  "problems": [],
  "searchResult": [
    {
      "sourceName": "Microsoft Visual Studio Offline Packages",
      "packages": []
    },
    {
      "sourceName": "gh-halospv3",
      "packages": [
        {
          "id": "HXE",
          "latestVersion": "2.1.3-ci.1",
          "totalDownloads": 0
        }
      ]
    },
    {
      "sourceName": "nuget.org",
      "packages": [
        {
          "id": "HXE",
          "latestVersion": "2.1.3-ci.1",
          "totalDownloads": 2715,
          "owners": "HaloSPV3"
        }
      ]
    }
  ]
}
```

**Comment by BinToss** [comment]
Good news!
I cobbled together `--dry-run`-like behavior for `dotnet nuget push` which runs via `semantic-release/cmd`. Because NuGet does not have `--dry-run`, I decided to package user-defined projects with `-p:PackageVersion=0.0.1-DUMMY` and push with `--skip-duplicate`. A new package version will be published on the first push, but subsequent pushes to that version will not fail nor overwrite the first `0.0.1-DUMMY`.
I'd implemented these dry-run `dotnet nuget push` commands to run during `prepare`, but it could easily be moved to `verifyConditions`. However, a `IsNextVersionAlreadyPublished` check should run A.S.A.P. after semantic release determines the `nextVersion` to quickly fail the release before `publish`. This means `IsNextVersionAlreadyPublished` must run during `prepare`.

I've written unit tests to check `NUGET_TOKEN`, GitHub PATs, and GitLab PATs all work locally, in an Act container, and in a real workflow run.

Bad news.
[Workflow `GITHUB_TOKEN` authentication is failing](https://github.com/HaloSPV3/HCE.Shared/actions/runs/16278670183/job/45963550476#step:15:489) and I can't figure out why. It's the last thing issue I need to iron out before publishing a pre-release.

<details><summary>Copy of workflow log error lines because the logs will eventually expire</summary>

```

✖ failing tests:

test at tests/dotnet/DotnetNugetPush.test.ts:21:9
✖ ...GITHUB_REPOSITORY_OWNER and GH_TOKEN are defined, valid, and can push packages to source  (6069.319266ms)
  Error: Command failed: dotnet nuget push "/tmp/HCE.Shared/.NET/Dummies/HCE.Shared.DeterministicNupkg/https___nuget.pkg.github.com_HaloSPV3/*.nupkg" --api-key *** --skip-duplicate --source https://nuget.pkg.github.com/HaloSPV3/index.json
  
  STDOUT:
    Pushing HCE.Shared.DeterministicNupkg.0.0.1-DUMMY.nupkg to 'https://nuget.pkg.github.com/HaloSPV3'...
      PUT https://nuget.pkg.github.com/HaloSPV3/
    warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
      Forbidden https://nuget.pkg.github.com/HaloSPV3/ 189ms
    error: Response status code does not indicate success: 403 (Forbidden).
    
  STDERR:
    
      at <anonymous> (/home/runner/work/HCE.Shared/HCE.Shared/src/utils/execAsync.ts:38:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async execAsync (/home/runner/work/HCE.Shared/HCE.Shared/src/utils/execAsync.ts:20:10)
      at async GithubNugetRegistryInfo._PushDummyPackages (/home/runner/work/HCE.Shared/HCE.Shared/src/dotnet/NugetRegistryInfo.ts:725:12)
      at async <anonymous> (/home/runner/work/HCE.Shared/HCE.Shared/src/dotnet/NugetRegistryInfo.ts:244:25)
      at async TestContext.<anonymous> (/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/DotnetNugetPush.test.ts:34:9)
      at async Test.run (node:internal/test_runner/test:1069:7)
      at async Promise.all (index 0)
      at async Suite.run (node:internal/test_runner/test:1466:7)
      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:332:3) {
    cmd: 'dotnet nuget push "/tmp/HCE.Shared/.NET/Dummies/HCE.Shared.DeterministicNupkg/https___nuget.pkg.github.com_HaloSPV3/*.nupkg" --api-key *** --skip-duplicate --source https://nuget.pkg.github.com/HaloSPV3/index.json',
    code: 1,
    killed: false,
    signal: null,
    stderr: '',
    stdout: "Pushing HCE.Shared.DeterministicNupkg.0.0.1-DUMMY.nupkg to 'https://nuget.pkg.github.com/HaloSPV3'...\n  PUT [https://nuget.pkg.github.com/HaloSPV3/\nwarn](https://nuget.pkg.github.com/HaloSPV3//nwarn) : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.\n  Forbidden https://nuget.pkg.github.com/HaloSPV3/ 189ms\nerror: Response status code does not indicate success: 403 (Forbidden).\n"
  }

```

</details>

<details><summary>Steps I've taken to troubleshoot it, if you're curious</summary>

- Add repo HCE.Shared with `write` to the package entry's [HaloSPV3 > Packages > HCE.Shared.DeterministicNupkg > Package settings > Manage Actions access](https://github.com/orgs/HaloSPV3/packages/nuget/HCE.Shared.DeterministicNupkg/settings#:~:text=Manage%20Actions%20access).
- Enable [HaloSPV3 > Packages > HCE.Shared.DeterministicNupkg > Package settings > Inherited Access](https://github.com/orgs/HaloSPV3/packages/nuget/HCE.Shared.DeterministicNupkg/settings#:~:test=Inherited%20access). Doesn't/shouldn't affect workflow token authorization.
- Set [HaloSPV3 > Repositories > HCE.Shared > Settings > Actions > General > Workflow permissions](https://github.com/HaloSPV3/HCE.Shared/settings/actions#:~:text=Workflow%20permissions) to read-only. `write` permissions in workflow files are explicitly required.
- Grant `GITHUB_TOKEN` `packages: write` in npm-release.yml
  - This is [passed from npm-release.yml to npm-ci-and-pack.yml via `secrets.GH_TOKEN`](https://github.com/HaloSPV3/HCE.Shared/actions/runs/16278670183/workflow#L7-L16) in a [`workflow_call`](https://github.com/HaloSPV3/HCE.Shared/blob/d233f4a424b687778b53c65d8705193ba41d867f/.github/workflows/npm-ci-and-pack.yml#L6-L21). _Is this the issue?_
- Log the first two characters of GH_TOKEN's value to check it isn't a weird value. As expected, they were `gh`. I reverted (`reset --hard`) that commit and force-pushed afterward.

</details>

**Comment by Kampfmoehre** [comment]
Ok, here is my suggestion:
We add a new config `verifyNugetApiAccessWithDummyPush` and a short explanation what it does in the Readme. It is an opt-in option, so people can decide if they want that extra protection for the sake of an additional dummy package.

You can open a PR with the changes, including unit tests and I will take a look at it
